baseurl = 'dat://e4af805791046dc8b531ba1b24ae6591295c70e9735479b42e8742d3ce180a3f/'

publishDir = 'public-dat'

# Disable comments by entering no Disqus shortname
disqusShortname = ""

[params.see_more]
    enable = true
    icon = "fa fa-2x fa-github"
    url  = "/" 
    title = "Project hosted on github,i.e. archived on zenodo."
    subtitle = "Also published at https://rdmpromotion.rbind.io"
    link_url = "https://github.com/open-science-promoters/RDM-promotion"
    link_text = "https://github.com/open-science-promoters/RDM-promotion"
    